version: "3.8"

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    command:
      ["--character-set-server=utf8", "--collation-server=utf8_unicode_ci"]
    volumes:
      - ./mariadb_data:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: "docker"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      MYSQL_ROOT_PASSWORD: "docker-root"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django
    restart: always
    volumes:
      - ./project:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
